package com.vaasudev.kmptest.domain.model

data class TripsListData(
    val id: Int,
    val pickUpLocation: String,
    val pickUpAddress: String = "",
    val dropOffLocation: String,
    val dropOffAddress: String = "",
    val bookDateTime: Long,
    val startDateTime: Long,
    val endDateTime: Long,
    val serviceData: Services,
    val status: String,
    val statusId: Int,
    val cancelTripFee: String = "",
    val driverName: String,
    val tripPrice: String,
    val tipped: String,
    val rating: String
)

val tripsListData = listOf(
    TripsListData(
        id = 1,
        pickUpLocation = "Café im Naturgarten",
        pickUpAddress = "Thaltej, Ahmedabad, Gujarat 380060",
        dropOffLocation = "ALDI Nord",
        dropOffAddress = "Tonnaer Str. 36A, 99947 Bad Langensalza, Germany",
        bookDateTime = 1754994960000,
        startDateTime = 1754994960000,
        endDateTime = 1754994960000,
        serviceData = getServicesData[0],
        status = "Cancelled",
        statusId = 4,
        cancelTripFee = "0.00",
        driverName = "Test Driver",
        tripPrice = "0.00",
        tipped = "0.00",
        rating = "0"
    ),
    TripsListData(
        id = 2,
        pickUpLocation = "Café im Naturgarten",
        pickUpAddress = "Thaltej, Ahmedabad, Gujarat 380060",
        dropOffLocation = "Griechisches Restaurant Herkules",
        dropOffAddress = "Steinweg 11, 99947 Bad Langensalza, Germany",
        bookDateTime = 1754849444000,
        startDateTime = 1754849684000,
        endDateTime = 1754851004000,
        serviceData = getServicesData[1],
        status = "Completed",
        statusId = 3,
        cancelTripFee = "0.00",
        driverName = "Karan Ambuja",
        tripPrice = "50.00",
        tipped = "0.00",
        rating = "4"
    ),
    TripsListData(
        id = 3,
        pickUpLocation = "Café im Naturgarten",
        pickUpAddress = "Thaltej, Ahmedabad, Gujarat 380060",
        dropOffLocation = "ALDI Nord",
        dropOffAddress = "Tonnaer Str. 36A, 99947 Bad Langensalza, Germany",
        bookDateTime = 1754745900000,
        startDateTime = 1754746260000,
        endDateTime = 1754747880000,
        serviceData = getServicesData[0],
        status = "Completed",
        statusId = 3,
        cancelTripFee = "0.00",
        driverName = "Kisho Natva",
        tripPrice = "150.00",
        tipped = "10.00",
        rating = "3"
    ),
    TripsListData(
        id = 4,
        pickUpLocation = "Café im Naturgarten",
        pickUpAddress = "Burggasse 10/11a, 99947 Bad Langensalza, Germany",
        dropOffLocation = "Arboretum Bad Langensalza",
        dropOffAddress = "Holzgasse 11, 99947 Bad Langensalza, Germany",
        bookDateTime = 1754218020000,
        startDateTime = 1754218020000,
        endDateTime = 1754218020000,
        serviceData = getServicesData[2],
        status = "Cancelled",
        statusId = 4,
        cancelTripFee = "10.00",
        driverName = "Amol Yeta",
        tripPrice = "0.00",
        tipped = "0.00",
        rating = "0"
    ),
    TripsListData(
        id = 5,
        pickUpLocation = "Café im Naturgarten",
        pickUpAddress = "Burggasse 10/11a, 99947 Bad Langensalza, Germany",
        dropOffLocation = "TRACO Park",
        dropOffAddress = "Poststraße 18, 99947 Bad Langensalza, Germany",
        bookDateTime = 1754245080000,
        startDateTime = 1754245680000,
        endDateTime = 1754246820000,
        serviceData = getServicesData[1],
        status = "Completed",
        statusId = 3,
        cancelTripFee = "0.00",
        driverName = "Kuna Xol",
        tripPrice = "89.00",
        tipped = "0.00",
        rating = "5"
    )
)
